# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# build.gradle files instead.
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m
android.useAndroidX=true
android.enableJetifier=true

# Version information
VERSION_CODE=1
VERSION_NAME=1.0.0
COMPILE_SDK=33
MIN_SDK=21
TARGET_SDK=33
